### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by claell** [davidstutz/mesh-voxelization#6]
I am currently looking for a fast CPU based voxelizer for mesh files and wondering, whether your project might fit my needs. I want to start from STL files and be able to get the voxelized version as a numpy array for further processing. Do you think that would be worth the required effort or are there better alternatives?

**Comment by davidstutz** [comment]
I am not super up-to-date on what code is out there. Based on my experience, you will have a hard time finding an out-of-the-box solution based on some common and well-tested library (otherwise, I wouldn't have written this code). So you will likely need to write parts yourself, or adapt existing code - which is likely to be research code. 

Easiest approach using this repository is as follows: convert your files to off files, run this tool with the right parameters, convert the HDF5 output to numpy arrays using h5py. This should not be too much work to get working.

Alternatively, you can try to adapt the code to STL files (only requires rewriting the `from_off` method in the code and try to save the result to something else than HDF5, also only requiring minor changes. This way you might get a solution that better fits your pipeline, for example, if you need to repeatedly process a lot of data for research.

**Comment by claell** [comment]
Alright, thanks for your fast and detailed reply!

After some more performance testing, I am currently using binvox on a Linux machine, which is acceptable for a grid size of 128.

I might have the time to look into this again, but it will probably be too time consuming to write the conversion script and look into how to build this.

**Comment by davidstutz** [comment]
No worries. Thanks for getting back.
